name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint (ruff) and Format (black --check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.6 black==24.8.0 yamllint==1.35.1
      - name: Ruff lint
        run: |
          ruff check src scripts || true
          # Fail only on errors (E/F); allow warnings in beginner repo
          ruff check --select E,F src scripts
      - name: Black check
        run: |
          black --check src scripts
      - name: YAML lint (k8s manifests)
        run: |
          yamllint -d '{extends: default, rules: {document-start: disable, line-length: {max: 140}}}' k8s

  python-smoke:
    name: Python import and script smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies (CPU-only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import check
        run: |
          python - <<'PY'
          import importlib
          for m in ["torch","fastapi","pydantic"]:
              importlib.import_module(m)
          print("Imports OK")
          PY
      - name: Train script smoke (short run)
        env:
          EPOCHS: '1'
          BATCH_SIZE: '64'
          LR: '0.001'
          MODEL_DIR: './model'
        run: |
          python src/train.py
          test -f ./model/model.pt

  docker-build:
    name: Build Docker images (no push)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build training image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.train
          push: false
          tags: mlops-demo-train:ci
      - name: Build serving image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.serve
          push: false
          tags: mlops-demo-serve:ci
